export const ARTICLE_LIST = "ARTICLE_LIST"
export const ARTICLE_LIST_SUCCEEDED = "ARTICLE_LIST_SUCCEEDED"
export const ARTICLE_LIST_FAILED = "ARTICLE_LIST_FAILED"

export const ARTICLE_READ = "ARTICLE_READ"
export const ARTICLE_READ_SUCCEEDED = "ARTICLE_READ_SUCCEEDED"
export const ARTICLE_READ_FAILED = "ARTICLE_READ_FAILED"

export const ARTICLE_ADD = "ARTICLE_ADD"
export const ARTICLE_ADD_SUCCEEDED = "ARTICLE_ADD_SUCCEEDED"
export const ARTICLE_ADD_FAILED = "ARTICLE_ADD_FAILED"

export const ARTICLE_DELETE = "ARTICLE_DELETE"
export const ARTICLE_DELETE_SUCCEEDED = "ARTICLE_DELETE_SUCCEEDED"
export const ARTICLE_DELETE_FAILED = "ARTICLE_DELETE_FAILED"

export const ARTICLE_EDIT = "ARTICLE_EDIT"
export const ARTICLE_EDIT_SUCCEEDED = "ARTICLE_EDIT_SUCCEEDED"
export const ARTICLE_EDIT_FAILED = "ARTICLE_EDIT_FAILED"